App\Entity\TTags:
    type: entity
    table: t_tags
    id:
        idtag:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        tags:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
        icon:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
    lifecycleCallbacks: {  }
