App\Entity\TUser:
    type: entity
    table: t_user
    id:
        iduser:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        username:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        password:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        email:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        createddate:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
        roles:
            type: array
            nullable: false
            length: 0
            options:
                fixed: false
        connected:
            type: boolean
            nullable: false
            options:
                default: '0'
    lifecycleCallbacks: {  }
